# Generated by Django 5.1.4 on 2024-12-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('usertype', models.CharField(choices=[('viewer', 'Viewer'), ('writer', 'Writer')], default='viewer', max_length=10)),
            ],
        ),
    ]
