# Generated by Django 5.1.4 on 2024-12-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writers_app', '0004_alter_blog_description_alter_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='user',
        ),
    ]
