# Generated by Django 5.1.4 on 2024-12-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers_app', '0005_rename_author_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
