# Generated by Django 5.1.4 on 2024-12-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers_app', '0006_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
